@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
@echo off
choco install dotnet4.5.1 -y
choco install dotnet3.5 -y
choco install vmwarevsphereclient -y
choco install vmwareworkstation -y
choco install firefox -y
choco install googlechrome -y
choco install flashplayerplugin -y
choco install jre8 -y
choco install flashplayeractivex -y
choco install 7zip.install -y
choco install notepadplusplus.install -y
choco install nodejs.install -y
choco install git.install -y
choco install vlc -y
choco install powershell -y
choco install atom -y
choco install silverlight -y
choco install putty -y
choco install libreoffice -y
choco install malwarebytes -y
choco install virtualbox -y
choco install vim -y
choco install wireshark -y
choco install wget -y
choco install curl -y
choco install winscp -y
choco install gimp -y
choco install python2 -y
choco install cygwin -y
choco install googledrive -y
choco install mumble -y
choco install visualstudiocode -y
